add: User, Booth, Transaction 모델 추가
GSM-Pay/Payment-API pull request #2
Opened 2020-06-25 09:19 UTC by startergate

2020-06-25 23:16 UTC, Unperknown requested changes
간단한 구현이라서 밑에 남긴 사소한 문제 빼고는 모두 괜찮을 것 같습니다. 추가적으로 구현할 게 없다면 Merge해도 좋을 것 같습니다.

2020-06-25 23:16 UTC, Unperknown commented on src/models/Booth.ts
> +  return user;
Booth 릴레이션에 대한 정의인데 user 변수로 명명하면 혼동이 있을 것 같습니다😶 사소할 수 있지만 이름을 booth 등으로 수정하면 좋을 것 같습니다.

2020-06-26 00:44 UTC, startergate commented on src/models/Booth.ts
> +  return user;
수정했습니다. 복붙하다가 안 고쳤네요 :(

2020-06-26 00:44 UTC, startergate commented
sync 해봤는데 오류가 터져서 고치고 있습니다.

2020-08-31 23:55 UTC, Unperknown approved these changes

2020-09-04 02:00 UTC, merged